#!/usr/bin/env python3
"""Generate docker-compose.test.yml — the isolated test override (design §4).

- nulls every container_name (!reset) so a -p voipbin-test project cannot
  collide with a live sandbox
- moves the fixed subnet 10.100.0.0/16 -> 10.199.0.0/16 and remaps the
  static ipv4_address entries into the new subnet
- pushes host-mutating / host-port services (kamailio, rtpengine, coredns,
  asterisk-*) into a 'host-mutating' profile so they are excluded unless the
  profile is explicitly activated
- strips ALL host port mappings (ports:) so the test project binds nothing
Idempotent: regenerates the file from the current docker-compose.yml.
"""
import re

SRC = "docker-compose.yml"
DST = "docker-compose.test.yml"

EXCLUDE = {"kamailio", "rtpengine", "coredns",
           "asterisk-call", "asterisk-conference", "asterisk-registrar",
           "asterisk-call-proxy", "asterisk-conference-proxy",
           "asterisk-registrar-proxy"}

lines = open(SRC).read().split("\n")
svc_line = next(i for i, l in enumerate(lines) if l.rstrip() == "services:")
vol_line = next(i for i, l in enumerate(lines) if l.rstrip() == "volumes:" and not l.startswith(" "))

services = []
for i in range(svc_line + 1, vol_line):
    m = re.match(r"^  ([a-zA-Z0-9_-]+):\s*$", lines[i])
    if m:
        services.append((m.group(1), i))

def block(idx):
    end = vol_line
    for name, s in services:
        if s > idx:
            end = s
            break
    return "\n".join(lines[idx:end])

out = [
    "# AUTO-GENERATED by scripts/_gen_test_override.py — do not edit by hand.",
    "# Isolated test override (design doc §4):",
    "#   docker compose -p voipbin-test -f docker-compose.yml -f docker-compose.test.yml ...",
    "# Guarantees: no container-name collisions with a live sandbox, a separate",
    "# subnet, no host port bindings, and no host-mutating VoIP services.",
    "",
    "services:",
]

for name, idx in services:
    b = block(idx)
    has_ports = re.search(r"^    ports:", b, re.M)
    m_ip = re.search(r"ipv4_address:\s*10\.100\.(\d+\.\d+)", b)
    # collect depends_on service names (both short and long form)
    deps = []
    m_dep = re.search(r"^    depends_on:\n((?:      .*\n?)+)", b, re.M)
    if m_dep:
        for dl in m_dep.group(1).split("\n"):
            dm = re.match(r"^      -\s*([a-zA-Z0-9_-]+)", dl) or re.match(r"^      ([a-zA-Z0-9_-]+):\s*$", dl)
            if dm:
                deps.append(dm.group(1))
    entry = [f"  {name}:", "    container_name: !reset null"]
    if has_ports:
        entry.append("    ports: !reset []")
    if m_ip:
        entry.append("    networks:")
        entry.append("      default:")
        entry.append(f"        ipv4_address: 10.199.{m_ip.group(1)}")
    if name in EXCLUDE:
        # !override: replace (not merge) any base-file profiles. Without it,
        # coredns's base 'internal-dns' profile would merge to the union
        # ["internal-dns","host-mutating"], and a mode-1 tree's
        # COMPOSE_PROFILES=internal-dns would re-enable it in the test project.
        # Uniform for all EXCLUDE services: semantically identical for the
        # ones with no base profile, and avoids special-casing coredns.
        entry.append('    profiles: !override ["host-mutating"]')
    elif deps and any(d in EXCLUDE for d in deps):
        kept = [d for d in deps if d not in EXCLUDE]
        # rewrite depends_on without the excluded services (preserve
        # service_healthy conditions for infra deps)
        entry.append("    depends_on: !override")
        for d in kept:
            cond = "service_healthy" if d in ("db", "redis", "rabbitmq") else "service_started"
            entry.append(f"      {d}:")
            entry.append(f"        condition: {cond}")
        if not kept:
            entry[-1] = "    depends_on: !reset {}"
    out += entry

out += [
    "",
    "networks:",
    "  default:",
    "    driver: bridge",
    "    ipam:",
    "      config:",
    "        - subnet: 10.199.0.0/16",
    "",
]

open(DST, "w").write("\n".join(out))
print(f"wrote {DST}: {len(services)} services, excluded={sorted(EXCLUDE)}")
